Add value to PropertyFilter
jomei/notionapi pull request #125
Opened 2023-01-17 02:56 UTC by joshmenden

I am needing to use the `/search` endpoint to the NotionAPI and was looking at [their docs](https://developers.notion.com/reference/post-search) for the endpoint. It looks like their `filter object` just has 2 attributes: `property` and `value`. By adding a `Value *string` property to the `PropertyFilter` type, you can successfully filter your queries like this —

```golang
desiredObjectType := "page"
response, err := client.Search.Do(context.Background(), &notionapi.SearchRequest{
  Query: "My Desired Page Title",
  Filter: notionapi.PropertyFilter{
    Property: "object",
      Value:    &desiredObjectType,
    },
  StartCursor: "",
  PageSize:    1,
})

response.Results[0] // returns a notionapi.Page object
```

2023-01-18 05:40 UTC, jomei requested changes
Hi! 
It looks like you edited the wrong struct. 
[Here](https://github.com/jomei/notionapi/blob/main/search.go#L44) the `Filter` property is defined as `interfase{}`, at the time I wrote that the actual structure of this property was unknown.
To fulfill your needs I suggest to add the `SearchFilter` struct like
```go
type SearchFilter struct {
  Value string `json:"value"`
  Property string `json:"property"`
}
```

WDYT?

2023-01-19 22:32 UTC, joshmenden commented
Nice I think that's an excellent idea! I just made those changes and gave them a test locally and it looks like it's working great. LMK if there are any other suggestions you have. Thanks for the library!

2023-01-23 10:16 UTC, jomei requested changes

2023-01-29 04:03 UTC, joshmenden commented on filter.go
> +func (f SearchFilter) filter() {}
Thank you so much for the direction, sorry for the confusion! This has been pushed up now.

2023-02-05 06:21 UTC, jomei approved these changes

2023-02-05 06:23 UTC, merged